services:
  app:
    build: .
    container_name: footie-app
    ports:
      - "3000:80"
    volumes:
      - .:/var/www/html
    networks:
      - shared-network
    command: >
      bash -c "chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache &&
              apache2-foreground"

networks:
  shared-network:
    external: true